version: '3.3' # optional since v1.27.0
services:
  redis:
    image: redis
    networks:
      - webnet
    ports:
      - '6379:6379'
  db:
    image: postgres
    networks:
      - webnet
    env_file:
      - database.env
    volumes:
      - ./database:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: calvin
      POSTGRES_PASSWORD: grand312
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   endpoint_mode: vip
  api:
    image: calvinrahmat/backend
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    ports:
      - '127.0.0.1:7100-7101:7123'
    command: ['./wait-for-it.sh', 'db:5432', '--', 'node', 'server.js']
  # front:
  #   tty: true
  #   image: calvinrahmat/front_blanja
  #   # ports:
  #   #   - '8080:3000'
  #   networks:
  #     - webnet
  #command: ['npm', 'start']
  # webserver:
  #   image: calvinrahmat/nginx_blanja
  #   depends_on:
  #     - api
  #     - front
  #   ports:
  #     - '80:80'
  #   networks:
  #     - webnet
networks:
  webnet:
volumes:
  database-data:
